spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/animationdb?serverTimezone=Asia/Seoul
    username: ani
    password: 1234
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update